package com.google.android.apps.customization.pixel;
/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int color_bundles = 0x7f010000;
    }

    public static final class color {
        public static final int color_primary_bundle1 = 0x7f020000;
        public static final int color_primary_bundle2 = 0x7f020001;
        public static final int color_primary_bundle3 = 0x7f020002;
        public static final int color_primary_default = 0x7f020003;
        public static final int color_primary_fruits1 = 0x7f020004;
        public static final int color_primary_fruits2 = 0x7f020005;
        public static final int color_primary_fruits3 = 0x7f020006;
        public static final int color_primary_fruits4 = 0x7f020007;
        public static final int color_primary_fruits5 = 0x7f020008;
        public static final int color_primary_rainbow1 = 0x7f020009;
        public static final int color_primary_rainbow2 = 0x7f02000a;
        public static final int color_primary_rainbow3 = 0x7f02000b;
        public static final int color_primary_rainbow4 = 0x7f02000c;
        public static final int color_primary_rainbow5 = 0x7f02000d;
        public static final int color_primary_rainbow6 = 0x7f02000e;
        public static final int color_primary_rainbow7 = 0x7f02000f;
        public static final int color_secondary_bundle1 = 0x7f020010;
        public static final int color_secondary_bundle2 = 0x7f020011;
        public static final int color_secondary_bundle3 = 0x7f020012;
        public static final int color_secondary_default = 0x7f020013;
        public static final int color_secondary_fruits1 = 0x7f020014;
        public static final int color_secondary_fruits2 = 0x7f020015;
        public static final int color_secondary_fruits3 = 0x7f020016;
        public static final int color_secondary_fruits4 = 0x7f020017;
        public static final int color_secondary_fruits5 = 0x7f020018;
        public static final int color_secondary_rainbow1 = 0x7f020019;
        public static final int color_secondary_rainbow2 = 0x7f02001a;
        public static final int color_secondary_rainbow3 = 0x7f02001b;
        public static final int color_secondary_rainbow4 = 0x7f02001c;
        public static final int color_secondary_rainbow5 = 0x7f02001d;
        public static final int color_secondary_rainbow6 = 0x7f02001e;
        public static final int color_secondary_rainbow7 = 0x7f02001f;
    }

    public static final class string {
        public static final int app_name = 0x7f030000;
        public static final int bundle1_color_name = 0x7f030001;
        public static final int bundle2_color_name = 0x7f030002;
        public static final int bundle3_color_name = 0x7f030003;
        public static final int bundle_name_bundle1 = 0x7f030004;
        public static final int bundle_name_bundle2 = 0x7f030005;
        public static final int bundle_name_bundle3 = 0x7f030006;
        public static final int bundle_name_default = 0x7f030007;
        public static final int bundle_name_fruits1 = 0x7f030008;
        public static final int bundle_name_fruits2 = 0x7f030009;
        public static final int bundle_name_fruits3 = 0x7f03000a;
        public static final int bundle_name_fruits4 = 0x7f03000b;
        public static final int bundle_name_fruits5 = 0x7f03000c;
        public static final int bundle_name_rainbow1 = 0x7f03000d;
        public static final int bundle_name_rainbow2 = 0x7f03000e;
        public static final int bundle_name_rainbow3 = 0x7f03000f;
        public static final int bundle_name_rainbow4 = 0x7f030010;
        public static final int bundle_name_rainbow5 = 0x7f030011;
        public static final int bundle_name_rainbow6 = 0x7f030012;
        public static final int bundle_name_rainbow7 = 0x7f030013;
        public static final int color_style_fruits1 = 0x7f030014;
        public static final int color_style_fruits2 = 0x7f030015;
        public static final int color_style_fruits3 = 0x7f030016;
        public static final int color_style_fruits4 = 0x7f030017;
        public static final int color_style_fruits5 = 0x7f030018;
        public static final int color_style_rainbow1 = 0x7f030019;
        public static final int color_style_rainbow2 = 0x7f03001a;
        public static final int color_style_rainbow3 = 0x7f03001b;
        public static final int color_style_rainbow4 = 0x7f03001c;
        public static final int color_style_rainbow5 = 0x7f03001d;
        public static final int color_style_rainbow6 = 0x7f03001e;
        public static final int color_style_rainbow7 = 0x7f03001f;
        public static final int default_color_name = 0x7f030020;
    }
}
